const nurseData = {
  location: {
    type: "Point",
    coordinates: [36.168477, 5.404361],
  },
  _id: "66c328441d1842d8b206d4a1",
  firstName: "Affaf",
  lastName: "Aissaoui",
  name: "Dounia Saidi 1",
  specialite: "Pediatric Nurse",
  phone: 1,
  password: "$2b$10$ffTYx6YvCLIj0ZsHS5sHFe/hr9SQ/OU0GLsW4oLwKe84b3.wq/qRC",
  email: "nurse1@gmail.com",
  sex: "woman",
  type: "nurse",
  nurseID: "4ce05e65-8c6e-4d0f-ba33-684f83853843",
  verificationCode: "82bf287e61a94262af3a",
  verified: false,
  demandingNewPassword: "false",
  online: false,
  tokenVersion: 0,
  profilePicture:
    "C:\\Users\\Administrator\\Desktop\\backend\\src\\images\\default\\anonymous.png",
  workStatus: "pending",
  ratingNumber: 0,
  ratingSum: 0,
  averageRating: 4.2,
  patientClients: 13,
  patientComments: [],
  available: [],
  patientRequests: [
    {
      location: {
        type: "Point",
        coordinates: [36.168477, 5.404361],
      },
      patient: "Chiheb Rahmouni 2",
      firstName: "Chiheb",
      lastName: "Rahmouni",
      phone: 2,
      status: "pending",
      nursesRequested: ["Dounia Saidi 1"],
      price: 500,
      service: "netoyage",
      subService: "tfol",
      patientRate: 0,
      distance: 2.6,
      choosen: false,
      userPatient: 10,
      time: "25 min",
      _id: "66c335f4f61637663e31dd9d",
    },
  ],
  __v: 3,
}; 
 export default nurseData;